# Generated by Django 4.2.23 on 2025-08-02 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_promotion_tour_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 1, 8, 4, 49, 472753, tzinfo=datetime.timezone.utc)),
        ),
    ]
