# Generated by Django 4.2.23 on 2025-08-23 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_promotion_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 22, 8, 16, 41, 895598, tzinfo=datetime.timezone.utc)),
        ),
    ]
