# Generated by Django 4.2.23 on 2025-09-06 07:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_promotion_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('room_type', models.CharField(choices=[('standard', 'Standard Room'), ('deluxe', 'Deluxe Room'), ('suite', 'Suite'), ('family', 'Family Room'), ('executive', 'Executive Room'), ('villa', 'Villa')], default='standard', max_length=20)),
                ('bed_type', models.CharField(choices=[('single', 'Single Bed'), ('twin', 'Twin Beds'), ('double', 'Double Bed'), ('queen', 'Queen Bed'), ('king', 'King Bed')], default='single', max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField(default=2, help_text='Maximum number of guests')),
                ('size', models.IntegerField(default=0, help_text='Room size in square meters')),
                ('services', models.TextField(blank=True, help_text='Comma-separated list of services')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Starting price for rooms', max_digits=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 6, 7, 17, 3, 628783, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='home.hotel'),
        ),
    ]
