# Generated by Django 4.2.23 on 2025-09-06 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_room_alter_hotel_price_alter_promotion_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='has_air_conditioning',
            field=models.BooleanField(default=True, help_text='Has air conditioning'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_bathrobes',
            field=models.BooleanField(default=False, help_text='Provides bathrobes'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_bathtub',
            field=models.BooleanField(default=False, help_text='Has bathtub'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_desk',
            field=models.BooleanField(default=True, help_text='Has desk'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_free_bottled_water',
            field=models.BooleanField(default=True, help_text='Provides free bottled water'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_hair_dryer',
            field=models.BooleanField(default=False, help_text='Has hair dryer'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_hot_water',
            field=models.BooleanField(default=True, help_text='Has hot water'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_mini_bar',
            field=models.BooleanField(default=False, help_text='Has mini bar'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_private_bathroom',
            field=models.BooleanField(default=True, help_text='Has private bathroom'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_refrigerator',
            field=models.BooleanField(default=False, help_text='Has refrigerator'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_shower',
            field=models.BooleanField(default=True, help_text='Has shower'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_toiletries',
            field=models.BooleanField(default=True, help_text='Provides toiletries'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_tv',
            field=models.BooleanField(default=True, help_text='Has TV'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_waiting_area',
            field=models.BooleanField(default=False, help_text='Has waiting area'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_non_smoking',
            field=models.BooleanField(default=True, help_text='Non-smoking room'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 6, 7, 25, 3, 975865, tzinfo=datetime.timezone.utc)),
        ),
    ]
